Update .github/workflows/codeberg.yml

diff --git a/.github/workflows/codeberg.yml b/.github/workflows/codeberg.yml
--- a/.github/workflows/codeberg.yml
+++ b/.github/workflows/codeberg.yml
@@ -28,9 +28,9 @@ jobs:
       - name: Mirror to Codeberg
         run: |
           if [[ "${{ github.event_name }}" == "push" ]]; then
-            git push --mirror codeberg
+            git push --mirror codeberg || echo "error"
           elif [[ "${{ github.event_name }}" == "delete" ]]; then
-            git push codeberg --delete ${{ github.ref_name }}
+            git push codeberg --delete ${{ github.ref_name }} || echo "error"
           fi
 
       - name: Remove Codeberg remote
